# Generated by Django 4.1.5 on 2023-01-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscriptiontype_advance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='advance',
        ),
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='basic',
        ),
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='professional',
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
