# Generated by Django 4.1.5 on 2023-01-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
