# Generated by Django 4.1.5 on 2023-01-17 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_subscriptiontype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_of_expiry',
            field=models.DateField(default=datetime.date(2023, 2, 16)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_of_purchase',
            field=models.DateField(default=datetime.date(2023, 1, 17)),
        ),
    ]
