# Generated by Django 4.1.5 on 2023-01-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_rename_date_ticket_ticket_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='description',
            new_name='ticket_description',
        ),
    ]
