# Generated by Django 4.1.5 on 2023-01-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_rename_description_ticket_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
