# Generated by Django 4.1.5 on 2023-01-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_ticket_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(default='Open', max_length=100, null=True),
        ),
    ]
