# Generated by Django 4.1.5 on 2023-01-17 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_alter_ticket_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 17, 7, 35, 54, 884177)),
        ),
    ]
