# Generated by Django 4.1.5 on 2023-01-17 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_ticket_ticket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_date',
            field=models.DateField(default=datetime.date(2023, 1, 17)),
        ),
    ]
